apiVersion: v1
kind: Service
metadata:
  name: m347-backend
  labels:
    app: m347-backend
spec:
  selector:
    app: m347-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP