name: 'Publish Docker Image'
description: 'Build and push Docker image to Docker Hub'
inputs:
  image-name:
    description: 'Name of the Docker image to be published'
    required: true
  context:
    description: 'Context for the Dockerfile'
    required: true
  docker-username:
    required: true
  docker-password:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: liuuner/${{ inputs.image-name }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: '${{ vars.REGISTRY }}/liuuner/${{ inputs.image-name }}'
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true