apiVersion: v1
kind: Service
metadata:
  name: m347-frontend
  labels:
    app: m347-frontend
spec:
  selector:
    app: m347-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP