apiVersion: v1
kind: Secret
metadata:
  name: m347-basic-auth
  annotations:
    argocd.argoproj.io/sync-options: Skip
    argocd.argoproj.io/hook: Skip
type: kubernetes.io/basic-auth
stringData:
  username: ""
  password: ""

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
