name: Publish Docker Images

on:
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Publish Backend
        uses: ./.github/actions/publish-docker
        with:
          image-name: 'm347-backend'
          context: './backend'
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Frontend
        uses: ./.github/actions/publish-docker
        with:
          image-name: 'm347-frontend'
          context: './frontend'
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}